services:
  backend:
    image: pablu/blinkscan-backend:latest
    ports: 
      - 8080:8080
    restart: no
    depends_on: 
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_SSL=disable

  db:
    image: postgres:latest
    restart: always
    shm_size: 512mb
    ports:
      - 5432:5432
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
