// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: session_queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
insert into session (
  account_id
) values (
  $1
)
RETURNING id, account_id, created
`

func (q *Queries) CreateSession(ctx context.Context, accountID pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, accountID)
	var i Session
	err := row.Scan(&i.ID, &i.AccountID, &i.Created)
	return i, err
}

const getUserForSession = `-- name: GetUserForSession :one
select a.id, name, base64_pwd_hash, base64_pwd_salt, s.id, account_id, created from account as a
join session as s on a.id = s.account_id
where s.id = $1
`

type GetUserForSessionRow struct {
	ID            pgtype.UUID
	Name          string
	Base64PwdHash string
	Base64PwdSalt string
	ID_2          pgtype.UUID
	AccountID     pgtype.UUID
	Created       pgtype.Timestamp
}

func (q *Queries) GetUserForSession(ctx context.Context, id pgtype.UUID) (GetUserForSessionRow, error) {
	row := q.db.QueryRow(ctx, getUserForSession, id)
	var i GetUserForSessionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Base64PwdHash,
		&i.Base64PwdSalt,
		&i.ID_2,
		&i.AccountID,
		&i.Created,
	)
	return i, err
}
